export const CONJUGATE_SNAPSHOT = [
  {
    conjugated: '들으면',
    infinitive: '듣다',
    conjugation_name: 'connective if',
    pronunciation: '드르면',
    romanized: 'deu-reu-myuhn',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'padchim + consonant -> insert 으 (들 + 면 -> 들으면)',
    ],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '듣고',
    infinitive: '듣다',
    conjugation_name: 'connective and',
    pronunciation: '듣고',
    romanized: 'deut-goh',
    reasons: ['join (듣 + 고 -> 듣고)'],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '듣지만',
    infinitive: '듣다',
    conjugation_name: 'connective but',
    pronunciation: '듣지만',
    romanized: 'deut-chee-mahn',
    reasons: ['join (듣 + 지만 -> 듣지만)'],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '들어',
    infinitive: '듣다',
    conjugation_name: 'declarative present informal low',
    pronunciation: '드러',
    romanized: 'deu-ruh',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 어 -> 들어)'],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들어요',
    infinitive: '듣다',
    conjugation_name: 'declarative present informal high',
    pronunciation: '드러요',
    romanized: 'deu-ruh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'join (들어 + 요 -> 들어요)',
    ],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '듣는다',
    infinitive: '듣다',
    conjugation_name: 'declarative present formal low',
    pronunciation: '든는다',
    romanized: 'deun-neun-dah',
    reasons: ['join (듣 + 는다 -> 듣는다)'],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '듣습니다',
    infinitive: '듣다',
    conjugation_name: 'declarative present formal high',
    pronunciation: '듣슴니다',
    romanized: 'deut-seum-nee-dah',
    reasons: ['join (듣 + 습니다 -> 듣습니다)'],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '들었어',
    infinitive: '듣다',
    conjugation_name: 'declarative past informal low',
    pronunciation: '드러써',
    romanized: 'deu-ruh-ssuh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 어 -> 들었어)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들었어요',
    infinitive: '듣다',
    conjugation_name: 'declarative past informal high',
    pronunciation: '드러써요',
    romanized: 'deu-ruh-ssuh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 어 -> 들었어)',
      'join (들었어 + 요 -> 들었어요)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '들었다',
    infinitive: '듣다',
    conjugation_name: 'declarative past formal low',
    pronunciation: '드러따',
    romanized: 'deu-ruh-ttah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 다 -> 들었다)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '들었습니다',
    infinitive: '듣다',
    conjugation_name: 'declarative past formal high',
    pronunciation: '드러씀니다',
    romanized: 'deu-ruh-sseum-nee-dah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 습니다 -> 들었습니다)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '들을 거야',
    infinitive: '듣다',
    conjugation_name: 'declarative future informal low',
    pronunciation: '드를 거야',
    romanized: 'deu-reul- -guh-yah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 을 -> 들을)',
      'join (들을 +  거야 -> 들을 거야)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들을 거예요',
    infinitive: '듣다',
    conjugation_name: 'declarative future informal high',
    pronunciation: '드를 거예요',
    romanized: 'deu-reul- -guh-yae-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 을 -> 들을)',
      'join (들을 +  거예요 -> 들을 거예요)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '들을 거다',
    infinitive: '듣다',
    conjugation_name: 'declarative future formal low',
    pronunciation: '드를 거다',
    romanized: 'deu-reul- -guh-dah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 을 -> 들을)',
      'join (들을 +  거다 -> 들을 거다)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '들을 겁니다',
    infinitive: '듣다',
    conjugation_name: 'declarative future formal high',
    pronunciation: '드를 검니다',
    romanized: 'deu-reul- -guhm-nee-dah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 을 -> 들을)',
      'join (들을 +  겁니다 -> 들을 겁니다)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '듣는',
    infinitive: '듣다',
    conjugation_name: 'determiner present',
    pronunciation: '든는',
    romanized: 'deun-neun',
    reasons: ['join (듣 + 는 -> 듣는)'],
    type: 'determiner',
    tense: 'present',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '들은',
    infinitive: '듣다',
    conjugation_name: 'determiner past',
    pronunciation: '드른',
    romanized: 'deu-reun',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 은 -> 들은)'],
    type: 'determiner',
    tense: 'past',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '들을',
    infinitive: '듣다',
    conjugation_name: 'determiner future',
    pronunciation: '드를',
    romanized: 'deu-reul',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 을 -> 들을)'],
    type: 'determiner',
    tense: 'future',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '들어',
    infinitive: '듣다',
    conjugation_name: 'imperative informal low',
    pronunciation: '드러',
    romanized: 'deu-ruh',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 어 -> 들어)'],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들어요',
    infinitive: '듣다',
    conjugation_name: 'imperative informal high',
    pronunciation: '드러요',
    romanized: 'deu-ruh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'join (들어 + 요 -> 들어요)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '들어라',
    infinitive: '듣다',
    conjugation_name: 'imperative formal low',
    pronunciation: '드러라',
    romanized: 'deu-ruh-rah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'join (들어 + 라 -> 들어라)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '들으십시오',
    infinitive: '듣다',
    conjugation_name: 'imperative formal high',
    pronunciation: '드르십씨오',
    romanized: 'deu-reu-sheep-shee-oh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'padchim + consonant -> insert 으 (들 + 십시오 -> 들으십시오)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '들어',
    infinitive: '듣다',
    conjugation_name: 'interrogative present informal low',
    pronunciation: '드러',
    romanized: 'deu-ruh',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 어 -> 들어)'],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들어요',
    infinitive: '듣다',
    conjugation_name: 'interrogative present informal high',
    pronunciation: '드러요',
    romanized: 'deu-ruh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'join (들어 + 요 -> 들어요)',
    ],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '듣느냐',
    infinitive: '듣다',
    conjugation_name: 'interrogative present formal low',
    pronunciation: '든느냐',
    romanized: 'deun-neu-nyah',
    reasons: ['join (듣 + 느냐 -> 듣느냐)'],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '듣습니까',
    infinitive: '듣다',
    conjugation_name: 'interrogative present formal high',
    pronunciation: '듣슴니까',
    romanized: 'deut-seum-nee-ggah',
    reasons: ['join (듣 + 습니까 -> 듣습니까)'],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '들었어',
    infinitive: '듣다',
    conjugation_name: 'interrogative past informal low',
    pronunciation: '드러써',
    romanized: 'deu-ruh-ssuh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 어 -> 들었어)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들었어요',
    infinitive: '듣다',
    conjugation_name: 'interrogative past informal high',
    pronunciation: '드러써요',
    romanized: 'deu-ruh-ssuh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 어 -> 들었어)',
      'join (들었어 + 요 -> 들었어요)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '들었느냐',
    infinitive: '듣다',
    conjugation_name: 'interrogative past formal low',
    pronunciation: '드런느냐',
    romanized: 'deu-ruhn-neu-nyah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 느냐 -> 들었느냐)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '들었습니까',
    infinitive: '듣다',
    conjugation_name: 'interrogative past formal high',
    pronunciation: '드러씀니까',
    romanized: 'deu-ruh-sseum-nee-ggah',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'vowel contraction [ㅓ ㅓ -> ㅓ] (들어 + 었 -> 들었)',
      'join (들었 + 습니까 -> 들었습니까)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '들음',
    infinitive: '듣다',
    conjugation_name: 'nominal ing',
    pronunciation: '드름',
    romanized: 'deu-reum',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 음 -> 들음)'],
    type: 'verbal noun',
    tense: 'none',
    speechLevel: 'none',
    honorific: false,
  },
  {
    conjugated: '들어',
    infinitive: '듣다',
    conjugation_name: 'propositive informal low',
    pronunciation: '드러',
    romanized: 'deu-ruh',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 어 -> 들어)'],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '들어요',
    infinitive: '듣다',
    conjugation_name: 'propositive informal high',
    pronunciation: '드러요',
    romanized: 'deu-ruh-yoh',
    reasons: [
      'ㄷ irregular (듣 -> 들)',
      'join (들 + 어 -> 들어)',
      'join (들어 + 요 -> 들어요)',
    ],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '듣자',
    infinitive: '듣다',
    conjugation_name: 'propositive formal low',
    pronunciation: '듣자',
    romanized: 'deut-chah',
    reasons: ['join (듣 + 자 -> 듣자)'],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '들읍시다',
    infinitive: '듣다',
    conjugation_name: 'propositive formal high',
    pronunciation: '드릅씨다',
    romanized: 'deu-reup-shee-dah',
    reasons: ['ㄷ irregular (듣 -> 들)', 'join (들 + 읍시다 -> 들읍시다)'],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: false,
  },
  {
    conjugated: '듣겠어',
    infinitive: '듣다',
    conjugation_name: 'suppositive informal low',
    pronunciation: '듣게써',
    romanized: 'deut-gae-ssuh',
    reasons: ['join (듣 + 겠어 -> 듣겠어)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'informal low',
    honorific: false,
  },
  {
    conjugated: '듣겠어요',
    infinitive: '듣다',
    conjugation_name: 'suppositive informal high',
    pronunciation: '듣게써요',
    romanized: 'deut-gae-ssuh-yoh',
    reasons: ['join (듣 + 겠어요 -> 듣겠어요)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'informal high',
    honorific: false,
  },
  {
    conjugated: '듣겠다',
    infinitive: '듣다',
    conjugation_name: 'suppositive formal low',
    pronunciation: '듣게따',
    romanized: 'deut-gae-ttah',
    reasons: ['join (듣 + 겠다 -> 듣겠다)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'formal low',
    honorific: false,
  },
  {
    conjugated: '듣겠습니다',
    infinitive: '듣다',
    conjugation_name: 'suppositive formal high',
    pronunciation: '듣게씀니다',
    romanized: 'deut-gae-sseum-nee-dah',
    reasons: ['join (듣 + 겠습니다 -> 듣겠습니다)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'formal high',
    honorific: false,
  },
];

export const CONJUGATE_ALWAYS_HONORIFIC_SNAPSHOT = [
  {
    conjugated: '계시면',
    infinitive: '계시다',
    conjugation_name: 'connective if',
    pronunciation: '계시면',
    romanized: 'gyae-shee-myuhn',
    reasons: ['join (계시 + 면 -> 계시면)'],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계시고',
    infinitive: '계시다',
    conjugation_name: 'connective and',
    pronunciation: '계시고',
    romanized: 'gyae-shee-goh',
    reasons: ['join (계시 + 고 -> 계시고)'],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계시지만',
    infinitive: '계시다',
    conjugation_name: 'connective but',
    pronunciation: '계시지만',
    romanized: 'gyae-shee-chee-mahn',
    reasons: ['join (계시 + 지만 -> 계시지만)'],
    type: 'connective',
    tense: 'none',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계셔',
    infinitive: '계시다',
    conjugation_name: 'declarative present informal low',
    pronunciation: '계셔',
    romanized: 'gyae-syuh',
    reasons: ['vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)'],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계세요',
    infinitive: '계시다',
    conjugation_name: 'declarative present informal high',
    pronunciation: '계세요',
    romanized: 'gyae-sae-yoh',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 세요 -> 계세요)',
    ],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계신다',
    infinitive: '계시다',
    conjugation_name: 'declarative present formal low',
    pronunciation: '계신다',
    romanized: 'gyae-sheen-dah',
    reasons: ['borrow padchim (계시 + 는다 -> 계신다)'],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계십니다',
    infinitive: '계시다',
    conjugation_name: 'declarative present formal high',
    pronunciation: '계심니다',
    romanized: 'gyae-sheem-nee-dah',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 십니다 -> 계십니다)',
    ],
    type: 'declarative present',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계셨어',
    infinitive: '계시다',
    conjugation_name: 'declarative past informal low',
    pronunciation: '계셔써',
    romanized: 'gyae-syuh-ssuh',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 어 -> 계셨어)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계셨어요',
    infinitive: '계시다',
    conjugation_name: 'declarative past informal high',
    pronunciation: '계셔써요',
    romanized: 'gyae-syuh-ssuh-yoh',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 어 -> 계셨어)',
      'join (계셨어 + 요 -> 계셨어요)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계셨다',
    infinitive: '계시다',
    conjugation_name: 'declarative past formal low',
    pronunciation: '계셔따',
    romanized: 'gyae-syuh-ttah',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 다 -> 계셨다)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계셨습니다',
    infinitive: '계시다',
    conjugation_name: 'declarative past formal high',
    pronunciation: '계셔씀니다',
    romanized: 'gyae-syuh-sseum-nee-dah',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 습니다 -> 계셨습니다)',
    ],
    type: 'declarative past',
    tense: 'past',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계실 거야',
    infinitive: '계시다',
    conjugation_name: 'declarative future informal low',
    pronunciation: '계실 거야',
    romanized: 'gyae-sheel- -guh-yah',
    reasons: [
      'borrow padchim (계시 + 을 -> 계실)',
      'join (계실 +  거야 -> 계실 거야)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계실 거예요',
    infinitive: '계시다',
    conjugation_name: 'declarative future informal high',
    pronunciation: '계실 거예요',
    romanized: 'gyae-sheel- -guh-yae-yoh',
    reasons: [
      'borrow padchim (계시 + 을 -> 계실)',
      'join (계실 +  거예요 -> 계실 거예요)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계실 거다',
    infinitive: '계시다',
    conjugation_name: 'declarative future formal low',
    pronunciation: '계실 거다',
    romanized: 'gyae-sheel- -guh-dah',
    reasons: [
      'borrow padchim (계시 + 을 -> 계실)',
      'join (계실 +  거다 -> 계실 거다)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계실 겁니다',
    infinitive: '계시다',
    conjugation_name: 'declarative future formal high',
    pronunciation: '계실 검니다',
    romanized: 'gyae-sheel- -guhm-nee-dah',
    reasons: [
      'borrow padchim (계시 + 을 -> 계실)',
      'join (계실 +  겁니다 -> 계실 겁니다)',
    ],
    type: 'declarative future',
    tense: 'future',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계시는',
    infinitive: '계시다',
    conjugation_name: 'determiner present',
    pronunciation: '계시는',
    romanized: 'gyae-shee-neun',
    reasons: ['join (계시 + 는 -> 계시는)'],
    type: 'determiner',
    tense: 'present',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계신',
    infinitive: '계시다',
    conjugation_name: 'determiner past',
    pronunciation: '계신',
    romanized: 'gyae-sheen',
    reasons: ['borrow padchim (계시 + 은 -> 계신)'],
    type: 'determiner',
    tense: 'past',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계실',
    infinitive: '계시다',
    conjugation_name: 'determiner future',
    pronunciation: '계실',
    romanized: 'gyae-sheel',
    reasons: ['borrow padchim (계시 + 을 -> 계실)'],
    type: 'determiner',
    tense: 'future',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계셔',
    infinitive: '계시다',
    conjugation_name: 'imperative informal low',
    pronunciation: '계셔',
    romanized: 'gyae-syuh',
    reasons: ['vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)'],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계세요',
    infinitive: '계시다',
    conjugation_name: 'imperative informal high',
    pronunciation: '계세요',
    romanized: 'gyae-sae-yoh',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 세요 -> 계세요)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계셔라',
    infinitive: '계시다',
    conjugation_name: 'imperative formal low',
    pronunciation: '계셔라',
    romanized: 'gyae-syuh-rah',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'join (계셔 + 라 -> 계셔라)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계십시오',
    infinitive: '계시다',
    conjugation_name: 'imperative formal high',
    pronunciation: '계십씨오',
    romanized: 'gyae-sheep-shee-oh',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 십시오 -> 계십시오)',
    ],
    type: 'imperative',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계셔',
    infinitive: '계시다',
    conjugation_name: 'interrogative present informal low',
    pronunciation: '계셔',
    romanized: 'gyae-syuh',
    reasons: ['vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)'],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계세요',
    infinitive: '계시다',
    conjugation_name: 'interrogative present informal high',
    pronunciation: '계세요',
    romanized: 'gyae-sae-yoh',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 세요 -> 계세요)',
    ],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계시느냐',
    infinitive: '계시다',
    conjugation_name: 'interrogative present formal low',
    pronunciation: '계시느냐',
    romanized: 'gyae-shee-neu-nyah',
    reasons: ['join (계시 + 느냐 -> 계시느냐)'],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계십니까',
    infinitive: '계시다',
    conjugation_name: 'interrogative present formal high',
    pronunciation: '계심니까',
    romanized: 'gyae-sheem-nee-ggah',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 십니까 -> 계십니까)',
    ],
    type: 'interrogative present',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계셨어',
    infinitive: '계시다',
    conjugation_name: 'interrogative past informal low',
    pronunciation: '계셔써',
    romanized: 'gyae-syuh-ssuh',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 어 -> 계셨어)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계셨어요',
    infinitive: '계시다',
    conjugation_name: 'interrogative past informal high',
    pronunciation: '계셔써요',
    romanized: 'gyae-syuh-ssuh-yoh',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 어 -> 계셨어)',
      'join (계셨어 + 요 -> 계셨어요)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계셨느냐',
    infinitive: '계시다',
    conjugation_name: 'interrogative past formal low',
    pronunciation: '계션느냐',
    romanized: 'gyae-syuhn-neu-nyah',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 느냐 -> 계셨느냐)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계셨습니까',
    infinitive: '계시다',
    conjugation_name: 'interrogative past formal high',
    pronunciation: '계셔씀니까',
    romanized: 'gyae-syuh-sseum-nee-ggah',
    reasons: [
      'vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)',
      'vowel contraction [ㅕ ㅓ -> ㅕ] (계셔 + 었 -> 계셨)',
      'join (계셨 + 습니까 -> 계셨습니까)',
    ],
    type: 'interrogative past',
    tense: 'past',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계심',
    infinitive: '계시다',
    conjugation_name: 'nominal ing',
    pronunciation: '계심',
    romanized: 'gyae-sheem',
    reasons: ['borrow padchim (계시 + 음 -> 계심)'],
    type: 'verbal noun',
    tense: 'none',
    speechLevel: 'none',
    honorific: true,
  },
  {
    conjugated: '계셔',
    infinitive: '계시다',
    conjugation_name: 'propositive informal low',
    pronunciation: '계셔',
    romanized: 'gyae-syuh',
    reasons: ['vowel contraction [ㅣ ㅓ -> ㅕ] (계시 + 어 -> 계셔)'],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계세요',
    infinitive: '계시다',
    conjugation_name: 'propositive informal high',
    pronunciation: '계세요',
    romanized: 'gyae-sae-yoh',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 세요 -> 계세요)',
    ],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계시자',
    infinitive: '계시다',
    conjugation_name: 'propositive formal low',
    pronunciation: '계시자',
    romanized: 'gyae-shee-chah',
    reasons: ['join (계시 + 자 -> 계시자)'],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계십시다',
    infinitive: '계시다',
    conjugation_name: 'propositive formal high',
    pronunciation: '계십씨다',
    romanized: 'gyae-sheep-shee-dah',
    reasons: [
      'honorific verb/adj -> remove 시 (계시 -> 계)',
      'join (계 + 십시다 -> 계십시다)',
    ],
    type: 'propositive',
    tense: 'present',
    speechLevel: 'formal high',
    honorific: true,
  },
  {
    conjugated: '계시겠어',
    infinitive: '계시다',
    conjugation_name: 'suppositive informal low',
    pronunciation: '계시게써',
    romanized: 'gyae-shee-gae-ssuh',
    reasons: ['join (계시 + 겠어 -> 계시겠어)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'informal low',
    honorific: true,
  },
  {
    conjugated: '계시겠어요',
    infinitive: '계시다',
    conjugation_name: 'suppositive informal high',
    pronunciation: '계시게써요',
    romanized: 'gyae-shee-gae-ssuh-yoh',
    reasons: ['join (계시 + 겠어요 -> 계시겠어요)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'informal high',
    honorific: true,
  },
  {
    conjugated: '계시겠다',
    infinitive: '계시다',
    conjugation_name: 'suppositive formal low',
    pronunciation: '계시게따',
    romanized: 'gyae-shee-gae-ttah',
    reasons: ['join (계시 + 겠다 -> 계시겠다)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'formal low',
    honorific: true,
  },
  {
    conjugated: '계시겠습니다',
    infinitive: '계시다',
    conjugation_name: 'suppositive formal high',
    pronunciation: '계시게씀니다',
    romanized: 'gyae-shee-gae-sseum-nee-dah',
    reasons: ['join (계시 + 겠습니다 -> 계시겠습니다)'],
    type: 'suppositive',
    tense: 'none',
    speechLevel: 'formal high',
    honorific: true,
  },
];
