export const FAVORITES = [
  {
    name: 'connective if',
    conjugation: '가면',
    romanization: 'gah-myuhn',
    tense: 'none',
    speechLevel: 'none',
    pronunciation: '가면',
    reasons: ['join (가 + 면 -> 가면)'],
    type: 'connective',
    honorific: false,
  },
  {
    name: 'declarative present informal low',
    conjugation: '가셔',
    romanization: 'gah-syuh',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가셔',
    reasons: [
      'join (가 + 시 -> 가시)',
      'vowel contraction [ㅣ ㅓ -> ㅕ] (가시 + 어 -> 가셔)',
    ],
    type: 'declarative present',
    honorific: true,
  },
  {
    name: 'propositive informal low',
    conjugation: '가',
    romanization: 'gah',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가',
    reasons: ['vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)'],
    type: 'propositive',
    honorific: false,
  },
];

export const CONJUGATIONS = [
  {
    name: 'connective if',
    conjugation: '가면',
    romanization: 'gah-myuhn',
    tense: 'none',
    speechLevel: 'none',
    pronunciation: '가면',
    reasons: ['join (가 + 면 -> 가면)'],
    type: 'connective',
    honorific: false,
  },
  {
    name: 'connective and',
    conjugation: '가고',
    romanization: 'gah-goh',
    tense: 'none',
    speechLevel: 'none',
    pronunciation: '가고',
    reasons: ['join (가 + 고 -> 가고)'],
    type: 'connective',
    honorific: false,
  },
  {
    name: 'connective but',
    conjugation: '가지만',
    romanization: 'gah-chee-mahn',
    tense: 'none',
    speechLevel: 'none',
    pronunciation: '가지만',
    reasons: ['join (가 + 지만 -> 가지만)'],
    type: 'connective',
    honorific: false,
  },
  {
    name: 'declarative present informal low',
    conjugation: '가',
    romanization: 'gah',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가',
    reasons: ['vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)'],
    type: 'declarative present',
    honorific: false,
  },
  {
    name: 'declarative present informal high',
    conjugation: '가요',
    romanization: 'gah-yoh',
    tense: 'present',
    speechLevel: 'informal high',
    pronunciation: '가요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'join (가 + 요 -> 가요)',
    ],
    type: 'declarative present',
    honorific: false,
  },
  {
    name: 'declarative present formal low',
    conjugation: '간다',
    romanization: 'gahn-dah',
    tense: 'present',
    speechLevel: 'formal low',
    pronunciation: '간다',
    reasons: ['borrow padchim (가 + 는다 -> 간다)'],
    type: 'declarative present',
    honorific: false,
  },
  {
    name: 'declarative present formal high',
    conjugation: '갑니다',
    romanization: 'gahm-nee-dah',
    tense: 'present',
    speechLevel: 'formal high',
    pronunciation: '감니다',
    reasons: ['borrow padchim (가 + 습니다 -> 갑니다)'],
    type: 'declarative present',
    honorific: false,
  },
  {
    name: 'declarative past informal low',
    conjugation: '갔어',
    romanization: 'gah-ssuh',
    tense: 'past',
    speechLevel: 'informal low',
    pronunciation: '가써',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 어 -> 갔어)',
    ],
    type: 'declarative past',
    honorific: false,
  },
  {
    name: 'declarative past informal high',
    conjugation: '갔어요',
    romanization: 'gah-ssuh-yoh',
    tense: 'past',
    speechLevel: 'informal high',
    pronunciation: '가써요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 어 -> 갔어)',
      'join (갔어 + 요 -> 갔어요)',
    ],
    type: 'declarative past',
    honorific: false,
  },
  {
    name: 'declarative past formal low',
    conjugation: '갔다',
    romanization: 'gah-ttah',
    tense: 'past',
    speechLevel: 'formal low',
    pronunciation: '가따',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 다 -> 갔다)',
    ],
    type: 'declarative past',
    honorific: false,
  },
  {
    name: 'declarative past formal high',
    conjugation: '갔습니다',
    romanization: 'gah-sseum-nee-dah',
    tense: 'past',
    speechLevel: 'formal high',
    pronunciation: '가씀니다',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 습니다 -> 갔습니다)',
    ],
    type: 'declarative past',
    honorific: false,
  },
  {
    name: 'declarative future informal low',
    conjugation: '갈 거야',
    romanization: 'gahl- -guh-yah',
    tense: 'future',
    speechLevel: 'informal low',
    pronunciation: '갈 거야',
    reasons: ['borrow padchim (가 + 을 -> 갈)', 'join (갈 +  거야 -> 갈 거야)'],
    type: 'declarative future',
    honorific: false,
  },
  {
    name: 'declarative future informal high',
    conjugation: '갈 거예요',
    romanization: 'gahl- -guh-yae-yoh',
    tense: 'future',
    speechLevel: 'informal high',
    pronunciation: '갈 거예요',
    reasons: [
      'borrow padchim (가 + 을 -> 갈)',
      'join (갈 +  거예요 -> 갈 거예요)',
    ],
    type: 'declarative future',
    honorific: false,
  },
  {
    name: 'declarative future formal low',
    conjugation: '갈 거다',
    romanization: 'gahl- -guh-dah',
    tense: 'future',
    speechLevel: 'formal low',
    pronunciation: '갈 거다',
    reasons: ['borrow padchim (가 + 을 -> 갈)', 'join (갈 +  거다 -> 갈 거다)'],
    type: 'declarative future',
    honorific: false,
  },
  {
    name: 'declarative future formal high',
    conjugation: '갈 겁니다',
    romanization: 'gahl- -guhm-nee-dah',
    tense: 'future',
    speechLevel: 'formal high',
    pronunciation: '갈 검니다',
    reasons: [
      'borrow padchim (가 + 을 -> 갈)',
      'join (갈 +  겁니다 -> 갈 겁니다)',
    ],
    type: 'declarative future',
    honorific: false,
  },
  {
    name: 'determiner present',
    conjugation: '가는',
    romanization: 'gah-neun',
    tense: 'present',
    speechLevel: 'none',
    pronunciation: '가는',
    reasons: ['join (가 + 는 -> 가는)'],
    type: 'determiner',
    honorific: false,
  },
  {
    name: 'determiner past',
    conjugation: '간',
    romanization: 'gahn',
    tense: 'past',
    speechLevel: 'none',
    pronunciation: '간',
    reasons: ['borrow padchim (가 + 은 -> 간)'],
    type: 'determiner',
    honorific: false,
  },
  {
    name: 'determiner future',
    conjugation: '갈',
    romanization: 'gahl',
    tense: 'future',
    speechLevel: 'none',
    pronunciation: '갈',
    reasons: ['borrow padchim (가 + 을 -> 갈)'],
    type: 'determiner',
    honorific: false,
  },
  {
    name: 'imperative informal low',
    conjugation: '가',
    romanization: 'gah',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가',
    reasons: ['vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)'],
    type: 'imperative',
    honorific: false,
  },
  {
    name: 'imperative informal high',
    conjugation: '가요',
    romanization: 'gah-yoh',
    tense: 'present',
    speechLevel: 'informal high',
    pronunciation: '가요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'join (가 + 요 -> 가요)',
    ],
    type: 'imperative',
    honorific: false,
  },
  {
    name: 'imperative formal low',
    conjugation: '가라',
    romanization: 'gah-rah',
    tense: 'present',
    speechLevel: 'formal low',
    pronunciation: '가라',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'join (가 + 라 -> 가라)',
    ],
    type: 'imperative',
    honorific: false,
  },
  {
    name: 'imperative formal high',
    conjugation: '가십시오',
    romanization: 'gah-sheep-shee-oh',
    tense: 'present',
    speechLevel: 'formal high',
    pronunciation: '가십씨오',
    reasons: ['join (가 + 십시오 -> 가십시오)'],
    type: 'imperative',
    honorific: false,
  },
  {
    name: 'interrogative present informal low',
    conjugation: '가',
    romanization: 'gah',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가',
    reasons: ['vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)'],
    type: 'interrogative present',
    honorific: false,
  },
  {
    name: 'interrogative present informal high',
    conjugation: '가요',
    romanization: 'gah-yoh',
    tense: 'present',
    speechLevel: 'informal high',
    pronunciation: '가요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'join (가 + 요 -> 가요)',
    ],
    type: 'interrogative present',
    honorific: false,
  },
  {
    name: 'interrogative present formal low',
    conjugation: '가느냐',
    romanization: 'gah-neu-nyah',
    tense: 'present',
    speechLevel: 'formal low',
    pronunciation: '가느냐',
    reasons: ['join (가 + 느냐 -> 가느냐)'],
    type: 'interrogative present',
    honorific: false,
  },
  {
    name: 'interrogative present formal high',
    conjugation: '갑니까',
    romanization: 'gahm-nee-ggah',
    tense: 'present',
    speechLevel: 'formal high',
    pronunciation: '감니까',
    reasons: ['borrow padchim (가 + 습니까 -> 갑니까)'],
    type: 'interrogative present',
    honorific: false,
  },
  {
    name: 'interrogative past informal low',
    conjugation: '갔어',
    romanization: 'gah-ssuh',
    tense: 'past',
    speechLevel: 'informal low',
    pronunciation: '가써',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 어 -> 갔어)',
    ],
    type: 'interrogative past',
    honorific: false,
  },
  {
    name: 'interrogative past informal high',
    conjugation: '갔어요',
    romanization: 'gah-ssuh-yoh',
    tense: 'past',
    speechLevel: 'informal high',
    pronunciation: '가써요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 어 -> 갔어)',
      'join (갔어 + 요 -> 갔어요)',
    ],
    type: 'interrogative past',
    honorific: false,
  },
  {
    name: 'interrogative past formal low',
    conjugation: '갔느냐',
    romanization: 'gahn-neu-nyah',
    tense: 'past',
    speechLevel: 'formal low',
    pronunciation: '간느냐',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 느냐 -> 갔느냐)',
    ],
    type: 'interrogative past',
    honorific: false,
  },
  {
    name: 'interrogative past formal high',
    conjugation: '갔습니까',
    romanization: 'gah-sseum-nee-ggah',
    tense: 'past',
    speechLevel: 'formal high',
    pronunciation: '가씀니까',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 았 -> 갔)',
      'join (갔 + 습니까 -> 갔습니까)',
    ],
    type: 'interrogative past',
    honorific: false,
  },
  {
    name: 'nominal ing',
    conjugation: '감',
    romanization: 'gahm',
    tense: 'none',
    speechLevel: 'none',
    pronunciation: '감',
    reasons: ['borrow padchim (가 + 음 -> 감)'],
    type: 'verbal noun',
    honorific: false,
  },
  {
    name: 'propositive informal low',
    conjugation: '가',
    romanization: 'gah',
    tense: 'present',
    speechLevel: 'informal low',
    pronunciation: '가',
    reasons: ['vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)'],
    type: 'propositive',
    honorific: false,
  },
  {
    name: 'propositive informal high',
    conjugation: '가요',
    romanization: 'gah-yoh',
    tense: 'present',
    speechLevel: 'informal high',
    pronunciation: '가요',
    reasons: [
      'vowel contraction [ㅏ ㅏ -> ㅏ] (가 + 아 -> 가)',
      'join (가 + 요 -> 가요)',
    ],
    type: 'propositive',
    honorific: false,
  },
  {
    name: 'propositive formal low',
    conjugation: '가자',
    romanization: 'gah-chah',
    tense: 'present',
    speechLevel: 'formal low',
    pronunciation: '가자',
    reasons: ['join (가 + 자 -> 가자)'],
    type: 'propositive',
    honorific: false,
  },
  {
    name: 'propositive formal high',
    conjugation: '갑시다',
    romanization: 'gahp-shee-dah',
    tense: 'present',
    speechLevel: 'formal high',
    pronunciation: '갑씨다',
    reasons: ['borrow padchim (가 + 읍시다 -> 갑시다)'],
    type: 'propositive',
    honorific: false,
  },
  {
    name: 'suppositive informal low',
    conjugation: '가겠어',
    romanization: 'gah-gae-ssuh',
    tense: 'none',
    speechLevel: 'informal low',
    pronunciation: '가게써',
    reasons: ['join (가 + 겠어 -> 가겠어)'],
    type: 'suppositive',
    honorific: false,
  },
  {
    name: 'suppositive informal high',
    conjugation: '가겠어요',
    romanization: 'gah-gae-ssuh-yoh',
    tense: 'none',
    speechLevel: 'informal high',
    pronunciation: '가게써요',
    reasons: ['join (가 + 겠어요 -> 가겠어요)'],
    type: 'suppositive',
    honorific: false,
  },
  {
    name: 'suppositive formal low',
    conjugation: '가겠다',
    romanization: 'gah-gae-ttah',
    tense: 'none',
    speechLevel: 'formal low',
    pronunciation: '가게따',
    reasons: ['join (가 + 겠다 -> 가겠다)'],
    type: 'suppositive',
    honorific: false,
  },
  {
    name: 'suppositive formal high',
    conjugation: '가겠습니다',
    romanization: 'gah-gae-sseum-nee-dah',
    tense: 'none',
    speechLevel: 'formal high',
    pronunciation: '가게씀니다',
    reasons: ['join (가 + 겠습니다 -> 가겠습니다)'],
    type: 'suppositive',
    honorific: false,
  },
];
