name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm ci
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SECRET }}'
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@main
