name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - name: Create env file
        run: echo $ENV_SECRETS > .env
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SECRET }}
