name: Deploy

on: 
  workflow_dispatch:
    inputs:
      promote:
        description: 'Promote deployment to receive all traffic'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - run: npm ci
      - name: Create env file
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Create Firebase json
        run: echo $FIREBASE_JSON >> hanji-bd63d-849ae0babd80.json
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SECRET }}'
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          promote: ${{ inputs.promote }}
