name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/738485251646/locations/global/workloadIdentityPools/github-deploy/providers/github-oidc-provider
          service_account: github-actions-account@hanji-server.iam.gserviceaccount.com
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@main
